package view;

import domain.Korisnik;
import domain.Radnik;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import server.Server;
import tableModel.KorisniciTableModel;

/**
 *
 * @author Nebojsa Brankovic
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private Server server;
    private int counter;

    public MainForm() {
        initComponents();
        this.server = null;
        counter = 0;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonStartServer = new javax.swing.JButton();
        jButtonStopServer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelStanje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelBrojPokrenutihKlijentskihAplikacija = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKorisnici = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serverska aplikacija");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Automehanicarska radnja");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        jButtonStartServer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonStartServer.setText("Start server");
        jButtonStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartServerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStartServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jButtonStopServer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonStopServer.setText("Stop server");
        jButtonStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopServerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonStopServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Trenutno stanje servera:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabelStanje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelStanje.setText("jLabel3");
        getContentPane().add(jLabelStanje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 152, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Broj pokrenutih klijentskih aplikacija:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabelBrojPokrenutihKlijentskihAplikacija.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBrojPokrenutihKlijentskihAplikacija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBrojPokrenutihKlijentskihAplikacija.setText("jLabel4");
        getContentPane().add(jLabelBrojPokrenutihKlijentskihAplikacija, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jTableKorisnici.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Korisnik", "Vreme povezivanja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableKorisnici.setRowHeight(30);
        jScrollPane1.setViewportView(jTableKorisnici);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 710, 520));

        jMenuSettings.setText("Podesavanja");

        jMenuItemConfig.setText("Konfiguracija servera");
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemConfig);

        jMenuBar1.add(jMenuSettings);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartServerActionPerformed
        if (server == null) {
            server = new Server(this);
            server.start();
            jLabelStanje.setText("AKTIVAN");
            jLabelStanje.setForeground(new Color(0, 255, 0).darker());
            System.out.println("Pokrenut server.");
        } else {
            JOptionPane.showMessageDialog(this, "Server je vec pokrenut");
        }
    }//GEN-LAST:event_jButtonStartServerActionPerformed

    private void jButtonStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopServerActionPerformed
        if (server != null) {
            server.stopServer();
            server = null;
            jLabelStanje.setText("UGASEN");
            jLabelStanje.setForeground(new Color(255, 0, 0));
        } else {
            JOptionPane.showMessageDialog(this, "Server je vec ugasen.");
        }
    }//GEN-LAST:event_jButtonStopServerActionPerformed

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigActionPerformed
        new ConfigForm().setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStartServer;
    private javax.swing.JButton jButtonStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBrojPokrenutihKlijentskihAplikacija;
    private javax.swing.JLabel jLabelStanje;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKorisnici;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        jLabelStanje.setText("UGASEN");
        jLabelStanje.setForeground(new Color(255, 0, 0));
        jLabelBrojPokrenutihKlijentskihAplikacija.setText("0");

        jTableKorisnici.setModel(new KorisniciTableModel());
    }

    public void addUser(Radnik radnik) {
        jLabelBrojPokrenutihKlijentskihAplikacija.setText(String.valueOf(++counter));
        Korisnik user = new Korisnik();
        user.setRadnik(radnik);
        user.setDatumPovezivanja(new Date());
        ((KorisniciTableModel) jTableKorisnici.getModel()).addUser(user);
    }

    public void removeUser(Radnik radnik) {
        jLabelBrojPokrenutihKlijentskihAplikacija.setText(String.valueOf(--counter));
        Korisnik user = new Korisnik();
        user.setRadnik(radnik);
        ((KorisniciTableModel) jTableKorisnici.getModel()).removeUser(user);

    }
}
